name: restart process after deployment

on:
  workflow_call:
    inputs:
      user:
        description: edge device username
        required: true
        type: string
      process-name:
        description: process name 
        required: true
        type: string
      slack-channel:
        description: after restart, send message to this slack channle
        required: true
        type: string
    secrets:
      password:
        description: edge device password
        required: true
      otp:
        description: edge device otp
        required: true

jobs:
  restart-after-deploy:
    name:   restart-after-deploy
    runs-on: self-hosted
    steps:
      - name: Checkout the deploy-target repository
        uses: actions/checkout@v2

      - name: Checkout the action repository
        uses: actions/checkout@v2
        with:
          repository: teamdable/vv-deploy-actions
          path: action/

      - name: Install python packages for api call
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt --extra-index-url ${{ secrets.extra-index-url }} --trusted-host ${{ secrets.trusted-host }}

      - name: Get VPN IP of deploy-target devices
        run: |
          action/get-vpn-ip

      - name: Kill and Start process
        run: |
          sudo apt-get install expect oathtool
          action/restart-process-after-deploy.sh ${{ inputs.user }} ${{ secrets.password }} ${{ secrets.otp }} ${{ inputs.process-name }} ${{ inputs.slack-channel }}